/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PinCode {
        "fieldsNumber": number;
    }
}
declare global {
    interface HTMLPinCodeElement extends Components.PinCode, HTMLStencilElement {
    }
    var HTMLPinCodeElement: {
        prototype: HTMLPinCodeElement;
        new (): HTMLPinCodeElement;
    };
    interface HTMLElementTagNameMap {
        "pin-code": HTMLPinCodeElement;
    }
}
declare namespace LocalJSX {
    interface PinCode {
        "fieldsNumber"?: number;
        "onEnter"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "pin-code": PinCode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pin-code": LocalJSX.PinCode & JSXBase.HTMLAttributes<HTMLPinCodeElement>;
        }
    }
}
